version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: fibo-postgres
    ports:
      - '5454:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=fibo
      - POSTGRES_USER=fibo
      - POSTGRES_DB=fibo
    networks:
      - network

volumes:
  postgres_data:
    name: 'fibo-postgres-data'

networks:
  network:
    name: 'fibo-network'
