apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/fibo-network: "true"
        io.kompose.service: migrate
    spec:
      containers:
        - args:
            - -database
            - postgres://fibo:fibo@postgres:5432/fibo?sslmode=disable
            - -path
            - /migrations
            - up
          image: migrate/migrate
          name: migrate
          volumeMounts:
            - mountPath: /migrations
              name: migrate-claim0
      restartPolicy: Always
      volumes:
        - name: migrate-claim0
          persistentVolumeClaim:
            claimName: migrate-claim0
